-- local lsp = require('lspconfig')
-- local config = require('helper.lsp_config')
--
-- local sumneko_root_path = '/home/user/language-servers/lua-language-server'
-- local sumneko_binary = sumneko_root_path .. '/bin/lua-language-server'

-- require'lspconfig'.lua_ls.setup{}
-- lsp.sumneko_lua.setup(config({
--     cmd = { sumneko_binary, "-E", sumneko_root_path .. "/main.lua" };
--     settings = {
--         Lua = {
--             runtime = {
--                 -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
--                 version = 'LuaJIT',
--                 -- Setup your lua path
--                 path = vim.split(package.path, ";"),
--             },
--             diagnostics = {
--                 -- Get the language server to recognize the `vim` global
--                 globals = { 'vim' },
--             },
--             workspace = {
--                 -- Make the server aware of Neovim runtime files
--                 library = {
--                     [vim.fn.expand("$VIMRUNTIME/lua")] = true,
--                     [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
--                 },
--             },
--             -- Do not send telemetry data containing a randomized but unique identifier
--             telemetry = {
--                 enable = false,
--             },
--         },
--     },
-- }))
