local harpoon_ui = require('harpoon.ui')
local harpoon_mark = require('harpoon.mark')

vim.keymap.set("n",'<leader>a', function () harpoon_mark.add_file() end)
vim.keymap.set("n",'//', function () harpoon_ui.toggle_quick_menu() end)
vim.keymap.set("n",'<leader>hu', function() harpoon_ui.nav_file(1) end)
vim.keymap.set("n",'<leader>he', function() harpoon_ui.nav_file(2) end)
vim.keymap.set("n",'<leader>ho', function() harpoon_ui.nav_file(3) end)
vim.keymap.set("n",'<leader>ha', function() harpoon_ui.nav_file(4) end)
vim.keymap.set("n",'<leader>h;', function() harpoon_ui.nav_file(5) end)
vim.keymap.set("n",'<leader>h,', function() harpoon_ui.nav_file(6) end)
